### ISSUE TITLE
Timers use infinite reservoir

### ISSUE THREAD

**Issue by kortemik** [teragrep/aer_01#26]
https://github.com/teragrep/aer_01/blob/79b1032ce0e8f3fbb7874cf3e30e6729eb2be77a/src/main/java/com/teragrep/aer_01/DefaultOutput.java#L100-L101

Should use a limited sample pool.

See example in https://github.com/teragrep/cfe_35/blob/main/src/main/java/com/teragrep/cfe_35/router/MessageParser.java#L95-L98

Please create documentation how to use the metrics library based on the pr https://github.com/teragrep/aer_01/commit/79b1032ce0e8f3fbb7874cf3e30e6729eb2be77a

**Comment by 51-code** [comment]
The fix has been implemented and currently in review. Starting to work on the documentation now.

**Comment by 51-code** [comment]
Internal docs for the metrics created.
